# Generated by Django 5.2.14 on 2026-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parentCategory', models.CharField(default='None', max_length=100)),
                ('slug', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=50)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('ordersCount', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('customerName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('paymentStatus', models.CharField(default='unpaid', max_length=50)),
                ('deliveryMethod', models.CharField(blank=True, max_length=100, null=True)),
                ('trackingNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('itemsCount', models.IntegerField(default=0)),
                ('items', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('originalPrice', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('costPrice', models.FloatField()),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.TextField(default='[]')),
                ('sizes', models.TextField(default='[]')),
                ('colors', models.TextField(default='[]')),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('seoKeywords', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=5.0)),
                ('reviewsCount', models.IntegerField(default=0)),
                ('inStock', models.IntegerField(default=1)),
                ('trending', models.IntegerField(default=0)),
                ('featured', models.IntegerField(default=0)),
                ('bestSeller', models.IntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('occasion', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
    ]
