# Generated by Django 5.2.14 on 2026-07-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_categorygroup_product_producttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limitedEdition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='newArrival',
            field=models.IntegerField(default=0),
        ),
    ]
