# Generated by Django 5.2.14 on 2026-07-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_limitededition_product_newarrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('logo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('seoTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('metaDescription', models.TextField(blank=True, null=True)),
                ('seoKeywords', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(default='percentage', max_length=50)),
                ('value', models.FloatField()),
                ('minPurchase', models.FloatField(default=0)),
                ('startDate', models.CharField(max_length=100)),
                ('endDate', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=50)),
                ('usageCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('customerName', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
