# Generated by Django 5.2.14 on 2026-07-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_brand_coupon_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exchangeRequest',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='order',
            name='returnRequest',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='order',
            name='reviews',
            field=models.TextField(default='{}'),
        ),
    ]
