# Generated by Django 5.2.14 on 2026-07-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_deliverydate_order_exchangerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='requiredSupercoins',
            field=models.IntegerField(default=0),
        ),
    ]
