# Generated by Django 5.2.14 on 2026-07-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_coupon_requiredsupercoins'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customerEmail', models.CharField(max_length=255)),
                ('customerName', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(default='Pending Verification', max_length=50)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
