# Generated by Django 5.2.14 on 2026-07-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderId', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
