# Generated by Django 5.2.14 on 2026-07-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='videoUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
